name: Build images

on:
  push:

jobs:
  build:
    runs-on: ubuntu-22.04
    services:
      osbuild-composer:
        image: ghcr.io/osbuild/osbuild-composer-container:centos-stream-9
        volumes:
          - /builds:/builds
        options: --privileged
    container:
      image: ghcr.io/osbuild/osbuild-composer-container:centos-stream-9
      volumes:
        - /builds:/builds
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run the build
        shell: bash
        run: |
          sleep 5
          tail --follow --lines +1 "/builds/osbuild-composer-journal.txt" &
          composer-cli() { /usr/bin/composer-cli --socket /builds/weldr-api.socket "$@"; }
          composer-cli sources add microshift.toml
          composer-cli sources add crio.toml
          composer-cli sources add kubic.toml
          composer-cli blueprints push microshift-blueprint-v0.0.1.toml
          compose_id=$(composer-cli --json compose start my-image qcow2 | jq -r ".[].body.build_id")
          while [[ $(composer-cli --json compose info "${compose_id}" | jq -r ".[].body.queue_status") =~ RUNNING|WAITING ]]; do sleep 15; done
          
          # check whether the build succeeded
          [[ $(composer-cli --json compose info "${compose_id}" | jq -r ".[].body.queue_status") =~ FINISHED ]] || exit 1
          
          composer-cli compose image "${compose_id}" --filename image.qcow2

      - name: Upload image artifacts
        uses: actions/upload-artifact@v3
        with:
          name: image.qcow2
          path: image.qcow2
